[book]
authors = ["Fran√ßois"]
language = "en"
multilingual = false
src = "src"
title = "Bevy Workshop"

[rust]
edition = "2024"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/vleue/bevy_workshop-rustweek-2025"
edit-url-template = "https://github.com/vleue/bevy_workshop-rustweek-2025/edit/main/bevy-workshop/{path}"
